[tools]
node = "lts"
python = "3.12"

[env]
env_file = ".env.local"
_.python.venv = { path = ".venv", create = true }


[tasks.setup]
description = "Set up development environment"
run = """
pip install -r requirements.txt
npm install
pre-commit install
"""

[tasks.pre-commit]
description = "Run pre-commit hooks on all files"
run = "pre-commit run --all"
